# Generated by Django 5.0 on 2024-04-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NagoyameshiApp', '0002_customuser_created_at_customuser_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
