# Generated by Django 5.0 on 2024-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NagoyameshiApp', '0004_alter_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='退会日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='サブスク契約'),
        ),
    ]
