# Generated by Django 5.0 on 2024-04-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NagoyameshiApp', '0004_alter_favorite_restaurant_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_max',
            field=models.PositiveIntegerField(default=0, verbose_name='価格（最大）'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_min',
            field=models.PositiveIntegerField(default=0, verbose_name='価格（最小）'),
        ),
    ]
