# Generated by Django 5.0 on 2024-07-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NagoyameshiApp', '0009_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='アカウント有効'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(verbose_name='更新日時'),
        ),
    ]
